### ISSUE TITLE
for the same route 

### ISSUE THREAD

**Issue by bxhz** [emiyalee1005/vue3-keep-alive-component#1]
For the same route but with different parameters, such as a detail page, the cached result causes both detail pages to display the same content. How can this be resolved?

**Comment by emiyalee1005** [comment]
You should watch the change for the route params

bxhz ***@***.***> 于 2024年6月5日周三 18:12写道：

**Comment by bxhz** [comment]
Is it possible to handle it uniformly by adding parameters to the component instead of  watch the change for the route params?

**Comment by emiyalee1005** [comment]
> Is it possible to handle it uniformly by adding parameters to the component instead of watch the change for the route params?

This is not how vue router work, anyway, if you want, you can make your own router component
